### ISSUE TITLE
Test & Update Swag Shop to be compatible with 1.10

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-swag-shop#51]
- [ ] - Test swag-shop with 1.10
- [ ] - If there are code or documentation changes that need to be made, make them
- [ ] - Update the README.md of this repo to note that this has been updated to be compatible with 1.9

**Comment by mori5ive** [comment]
Exception from sub Products id PsZLbCdjjsJqz2ZMx TypeError: findProductMedia is not a function
    at Subscription.publishFeaturedSwagProducts [as _handler] (imports/plugins/custom/reaction-swag-shop/server/publications/collections/products.js:401:27)
    at packages/check/match.js:108:16
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:107:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
    at DDP._CurrentPublicationInvocation.withValue (packages/ddp-server/livedata_server.js:1043:15)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at Subscription._runHandler (packages/ddp-server/livedata_server.js:1041:51)
    at Session._startSubscription (packages/ddp-server/livedata_server.js:859:9)
    at Session.sub (packages/ddp-server/livedata_server.js:625:12)
    at packages/ddp-server/livedata_server.js:559:43

**Comment by mori5ive** [comment]
where is findProductMedia? this method deleted from publications

**Comment by prinzdezibel** [comment]
@mori5ive I'm in the process updating swag shop to match the source code of release-1.9.0. It's completely broken right now due to breaking changes. I'll keep you updated.

**Comment by mori5ive** [comment]
@prinzdezibel thank, when new updates release?

**Comment by prinzdezibel** [comment]
Merged into master. Going to close.
