### ISSUE TITLE
meteor/aldeed:simple-schema & simpl-schema issue

### ISSUE THREAD

**Issue by hungphidev** [reactioncommerce/reaction-swag-shop#53]
I get an error after clone and run reaction with reaction-swag-shop plugin:
`Error: Cannot find module 'meteor/aldeed:simple-schema'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.require (/home/pkhung/ecomerceProject/newecomm/.meteor/local/build/programs/server/boot.js:288:32)
    at makeInstallerOptions.fallback (packages/modules-runtime.js:651:18)
    at require (packages/modules-runtime.js:244:16)
    at tags.js (imports/plugins/custom/reaction-swag-shop/lib/collections/schemas/tags.js:1:31)`

Console told me that package meteor/aldeed:simple-schema is missing. So I run `meteor add aldeed:simple-schema` and restart reaction again but still get an error about SimpleSchema: 
`Error: Invalid definition for pick field.
    at packages/aldeed_simple-schema.js:1429:13
    at Function._.each._.forEach (packages/underscore.js:147:22)
    at new SimpleSchema (packages/aldeed_simple-schema.js:1426:5)
    at tags.js (imports/plugins/custom/reaction-swag-shop/lib/collections/schemas/tags.js:6:19)`

I try to change `import { SimpleSchema } from "meteor/aldeed:simple-schema";` 
to `import SimpleSchema from "simpl-schema";` in two file **swagProducts.js** and **tags.js**. But still get error: 
`Error: You may not pass an array of schemas to the SimpleSchema constructor or to extend()
    at SimpleSchema.extend (/home/pkhung/ecomerceProject/avgecomm/node_modules/simpl-schema/dist/SimpleSchema.js:564:40)
    at new SimpleSchema (/home/pkhung/ecomerceProject/avgecomm/node_modules/simpl-schema/dist/SimpleSchema.js:138:10)
    at tags.js (imports/plugins/custom/reaction-swag-shop/lib/collections/schemas/tags.js:7:19)`

Please help!
P/S: I find that reaction now using npm package 'simpl-schema' instead of 'aldeed:simple-schema'.

**Comment by zenweasel** [comment]
@hungphidev Please pull the current version on `master` and you should be fine

**Comment by hungphidev** [comment]
@zenweasel Thank Brent! It solved
