### ISSUE TITLE
Cannot find module '../../../../../core/collections

### ISSUE THREAD

**Issue by tienloinguyen22** [reactioncommerce/reaction-swag-shop#62]
C:\Users\tienl\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\server-lib\node_modules\fibers\future.js:280
                                                throw(ex);
                                                ^

Error: Cannot find module '../../../../../core/collections'
    at makeMissingError (packages\modules-runtime.js:231:12)
    at require (packages\modules-runtime.js:241:19)
    at tags.js (imports/plugins/custom/reaction-swag-shop/lib/collections/schemas/tags.js:1:29)
    at fileEvaluate (packages\modules-runtime.js:343:9)
    at require (packages\modules-runtime.js:238:16)
    at index.js (imports/plugins/custom/reaction-swag-shop/lib/collections/schemas/index.js:1:14)
    at fileEvaluate (packages\modules-runtime.js:343:9)
    at require (packages\modules-runtime.js:238:16)
    at index.js (imports/plugins/custom/reaction-swag-shop/server/index.js:1:14)
    at fileEvaluate (packages\modules-runtime.js:343:9)
    at require (packages\modules-runtime.js:238:16)
    at plugins.js (server/plugins.js:1:3419)
    at fileEvaluate (packages\modules-runtime.js:343:9)
    at require (packages\modules-runtime.js:238:16)
    at C:\Users\tienl\OneDrive\Desktop\reaction-commerce\.meteor\local\build\programs\server\app\app.js:110338:1
    at C:\Users\tienl\OneDrive\Desktop\reaction-commerce\.meteor\local\build\programs\server\boot.js:411:36
    at Array.forEach (<anonymous>)
    at C:\Users\tienl\OneDrive\Desktop\reaction-commerce\.meteor\local\build\programs\server\boot.js:220:19
    at C:\Users\tienl\OneDrive\Desktop\reaction-commerce\.meteor\local\build\programs\server\boot.js:471:5
    at Function.run (C:\Users\tienl\OneDrive\Desktop\reaction-commerce\.meteor\local\build\programs\server\profile.js:510:12)
    at C:\Users\tienl\OneDrive\Desktop\reaction-commerce\.meteor\local\build\programs\server\boot.js:470:11
=> Exited with code: 1

I'm having this issue while trying to run reaction swag shop . Is anyone have a solution ??

**Comment by Akarshit** [comment]
Being tracked in #61
